### PR TITLE
fix: 439 probes spawn in with a green ish color regardless of their actual color

### LINKED ISSUE #439: Probes spawn in with a green-ish color regardless of their actual color
A probe could have a blue or orange color, but the material on it is a dark green. If you choose a new color it will then update properly.

Reproduce this by dropping a new probe into the scene and notice that it is not the same color as what is shown in the quick settings panel.

### PR DESCRIPTION
**Pull request by kjy5**
fixes #439

### CODE REVIEW

**Comment by dbirman** [comment]
This isn't the solution to this problem -- it will break other code downstream because setting Color in Awake() triggers other functions that haven't run their own Awake yet. More generally I think it's good practice for Awake to not interact with other classes.

The reason _color is being set here was so that the internal color is set properly, and then the idea was to trigger in Start() an extra call to the ProbePanels and Renderer to update their colors. This is working properly for the probe panels but I think it's not getting passed properly to the renderer. So we should revert this change and fix that instead.

**Comment by kjy5** [comment]
Oh, I didn't know that! I thought it was just a typo there

**Comment by kjy5** [comment]
I will revert that

**Comment by dbirman** [comment]
Also re-open the issue and assign it to me, I'll debug this today (or you can debug it if you want to play around with how Awake/Start interact across components!)

**Comment by kjy5** [comment]
I'm going to work on #290 first, then come back to this

**Pull request merged**
